export const B = Object.freeze({
  AIR: 0,
  GRASS: 1,
  DIRT: 2,
  STONE: 3,
  SAND: 4,
  LOG: 5,
  LEAVES: 6,
  PLANKS: 7,
  COBBLE: 8,
  GLASS: 9,
  BRICKS: 10,
  WATER: 11,
  COAL_ORE: 12,
  IRON_ORE: 13,
  CRYSTAL_ORE: 14,
  SNOW: 15,
  WORKBENCH: 16,
  LANTERN: 17,
  BASALT: 18,
  CLAY: 19,
  WOOL: 20,
  CAMPFIRE: 21,
  BEDROCK: 22,
  FURNACE: 23,
  TORCH: 24,
  BED: 25,
  OBSIDIAN: 33,
  PORTAL_X: 34,
  PORTAL_Z: 35,
  NETHERRACK: 36,
  LAVA: 37,
  NETHER_BRICKS: 38,
  BLACKSTONE: 39,
  GOLD_BLOCK: 40,
  CHEST: 41,
  SOUL_SAND: 42,
  GLOWSTONE: 43,
  GRAVEL: 44,
  NETHER_GOLD: 45,
  NETHER_WART: 46,
  SPAWNER: 47,
});

export const BLOCKS = {
  0: { name: 'Air', solid: false, transparent: true },
  1: {
    name: 'Grass',
    color: '#7eaa43',
    tiles: [1, 1, 0, 2, 1, 1],
    hardness: 0.5,
    drop: 2,
    category: 'Earth',
  },
  2: { name: 'Dirt', color: '#916341', tile: 2, hardness: 0.4, category: 'Earth' },
  3: { name: 'Stone', color: '#88938c', tile: 3, hardness: 1.8, drop: 8, category: 'Earth' },
  4: { name: 'Sand', color: '#dfcc92', tile: 4, hardness: 0.4, category: 'Earth' },
  5: {
    name: 'Oak log',
    color: '#91643b',
    tiles: [5, 5, 6, 6, 5, 5],
    hardness: 1.2,
    category: 'Nature',
  },
  6: { name: 'Oak leaves', color: '#50813c', tile: 7, hardness: 0.2, category: 'Nature' },
  7: { name: 'Oak planks', color: '#c39860', tile: 8, hardness: 0.8, category: 'Building' },
  8: { name: 'Cobblestone', color: '#78857f', tile: 9, hardness: 1.5, category: 'Building' },
  9: {
    name: 'Glass',
    color: '#abd7d6',
    tile: 10,
    hardness: 0.3,
    transparent: true,
    category: 'Building',
  },
  10: { name: 'Clay bricks', color: '#a96f57', tile: 11, hardness: 1.4, category: 'Building' },
  11: {
    name: 'Water',
    color: '#488ba0',
    tile: 12,
    hardness: 0,
    solid: false,
    transparent: true,
    liquid: true,
    category: 'Nature',
  },
  12: {
    name: 'Coal ore',
    color: '#505d57',
    tile: 13,
    hardness: 2,
    drop: 91,
    tier: 1,
    category: 'Earth',
  },
  13: {
    name: 'Iron ore',
    color: '#b19983',
    tile: 14,
    hardness: 2.4,
    drop: 95,
    tier: 1,
    category: 'Earth',
  },
  14: {
    name: 'Crystal ore',
    color: '#71cbd1',
    tile: 15,
    hardness: 3,
    drop: 94,
    tier: 2,
    category: 'Earth',
  },
  15: { name: 'Snow', color: '#e9eee8', tile: 16, hardness: 0.4, category: 'Nature' },
  16: {
    name: 'Crafting Table',
    color: '#b88852',
    tiles: [18, 18, 17, 8, 18, 18],
    hardness: 1,
    category: 'Building',
  },
  17: {
    name: 'Lantern',
    color: '#ffc975',
    tile: 19,
    hardness: 0.4,
    model: 'lantern',
    transparent: true,
    solid: false,
    category: 'Decoration',
  },
  18: { name: 'Basalt', color: '#424e50', tile: 20, hardness: 2, category: 'Building' },
  19: {
    name: 'Clay',
    color: '#b99e86',
    tile: 21,
    hardness: 0.5,
    drop: 96,
    dropCount: 4,
    category: 'Earth',
  },
  20: { name: 'Ivory wool', color: '#f1e5c9', tile: 22, hardness: 0.4, category: 'Building' },
  21: {
    name: 'Campfire',
    color: '#d89b49',
    tile: 19,
    hardness: 0.6,
    model: 'campfire',
    transparent: true,
    solid: false,
    category: 'Decoration',
  },
  22: { name: 'Bedrock', color: '#363c41', tile: 23, hardness: Infinity, category: 'Earth' },
  23: {
    name: 'Furnace',
    color: '#8c918d',
    tiles: [9, 9, 3, 3, 24, 9],
    hardness: 3.5,
    tier: 1,
    category: 'Building',
  },
  24: {
    name: 'Torch',
    color: '#efbf61',
    tile: 19,
    hardness: 0.1,
    model: 'torch',
    transparent: true,
    solid: false,
    category: 'Decoration',
  },
};
for (let facing = 0; facing < 4; facing++) {
  for (let head = 0; head < 2; head++) {
    BLOCKS[25 + facing * 2 + head] = {
      name: 'Red Bed',
      color: '#b93f43',
      tile: 25,
      hardness: 0.3,
      bed: true,
      bedHead: !!head,
      facing,
      height: 0.5625,
      transparent: true,
      model: head ? 'bed_head' : 'bed_foot',
      drop: 25,
      stackSize: 1,
      hidden: facing !== 0 || head !== 0,
      category: 'Supplies',
    };
  }
}
Object.assign(BLOCKS, {
  33: { name: 'Obsidian', color: '#33263f', tile: 26, hardness: 10, tier: 4, category: 'Building' },
  34: {
    name: 'Nether Portal',
    color: '#b056e3',
    tile: 27,
    hardness: Infinity,
    solid: false,
    transparent: true,
    model: 'portal_x',
    hidden: true,
  },
  35: {
    name: 'Nether Portal',
    color: '#b056e3',
    tile: 27,
    hardness: Infinity,
    solid: false,
    transparent: true,
    model: 'portal_z',
    hidden: true,
  },
  36: { name: 'Netherrack', color: '#8e3938', tile: 28, hardness: 0.4, category: 'Earth' },
  37: {
    name: 'Lava',
    color: '#f98428',
    tile: 29,
    hardness: Infinity,
    solid: false,
    transparent: true,
    liquid: true,
    category: 'Nature',
  },
  38: { name: 'Nether Bricks', color: '#45272e', tile: 30, hardness: 2, category: 'Building' },
  39: { name: 'Blackstone', color: '#423c46', tile: 31, hardness: 1.5, category: 'Building' },
  40: {
    name: 'Block of Gold',
    color: '#edc94f',
    tile: 32,
    hardness: 3,
    tier: 3,
    category: 'Building',
  },
  41: {
    name: 'Chest',
    color: '#af773c',
    tile: 33,
    hardness: 2.5,
    model: 'chest',
    height: 0.875,
    transparent: true,
    category: 'Building',
  },
  42: { name: 'Soul Sand', color: '#655145', tile: 34, hardness: 0.5, category: 'Earth' },
  43: { name: 'Glowstone', color: '#f7d585', tile: 35, hardness: 0.3, category: 'Decoration' },
  44: { name: 'Gravel', color: '#a29991', tile: 36, hardness: 0.6, category: 'Earth' },
  45: {
    name: 'Nether Gold Ore',
    color: '#bc7046',
    tile: 37,
    hardness: 1,
    tier: 1,
    drop: 138,
    dropCount: 3,
    category: 'Earth',
  },
  46: {
    name: 'Nether Wart',
    color: '#bb333d',
    tile: 38,
    hardness: 0.1,
    solid: false,
    transparent: true,
    model: 'wart',
    category: 'Nature',
  },
  47: {
    name: 'Blaze Spawner',
    color: '#393c48',
    tile: 39,
    hardness: 5,
    drop: 0,
    model: 'spawner',
    transparent: true,
    category: 'Building',
  },
});
for (const [id, block] of Object.entries(BLOCKS)) {
  block.id = Number(id);
  block.solid ??= true;
  block.transparent ??= false;
  block.drop ??= Number(id);
}

export const ITEMS = {
  ...BLOCKS,
  90: { id: 90, name: 'Stick', color: '#b88752', category: 'Materials' },
  91: { id: 91, name: 'Coal', color: '#3c4445', category: 'Materials' },
  92: { id: 92, name: 'Iron Ingot', color: '#ced5cb', category: 'Materials' },
  93: {
    id: 93,
    name: 'Wild berries',
    color: '#d26978',
    food: 2,
    saturation: 0.4,
    category: 'Supplies',
  },
  94: { id: 94, name: 'Crystal', color: '#80dedd', category: 'Materials' },
  95: { id: 95, name: 'Raw Iron', color: '#c7a98d', category: 'Materials' },
  96: { id: 96, name: 'Clay Ball', color: '#acb4b5', category: 'Materials' },
  97: { id: 97, name: 'Brick', color: '#bf795e', category: 'Materials' },
  98: { id: 98, name: 'Iron Nugget', color: '#ced5cb', category: 'Materials' },
  99: { id: 99, name: 'String', color: '#ece5d2', category: 'Materials' },
  100: {
    id: 100,
    name: 'Wooden pickaxe',
    color: '#b18853',
    tier: 1,
    speed: 2,
    tool: true,
    durability: 59,
    category: 'Tools',
  },
  101: {
    id: 101,
    name: 'Stone pickaxe',
    color: '#939c90',
    tier: 2,
    speed: 3.5,
    tool: true,
    durability: 131,
    category: 'Tools',
  },
  102: {
    id: 102,
    name: 'Iron pickaxe',
    color: '#d8ded8',
    tier: 3,
    speed: 5.5,
    tool: true,
    durability: 250,
    category: 'Tools',
  },
  103: {
    id: 103,
    name: 'Iron sword',
    color: '#d8ded8',
    tool: true,
    durability: 250,
    damage: 6,
    category: 'Tools',
  },
  104: {
    id: 104,
    name: 'Crystal pickaxe',
    color: '#80dedd',
    tier: 4,
    speed: 8,
    tool: true,
    durability: 1561,
    category: 'Tools',
  },
  110: {
    id: 110,
    name: 'Iron Helmet',
    color: '#ced5cb',
    armor: 0,
    protection: 2,
    durability: 165,
    category: 'Equipment',
  },
  111: {
    id: 111,
    name: 'Iron Chestplate',
    color: '#ced5cb',
    armor: 1,
    protection: 6,
    durability: 240,
    category: 'Equipment',
  },
  112: {
    id: 112,
    name: 'Iron Leggings',
    color: '#ced5cb',
    armor: 2,
    protection: 5,
    durability: 225,
    category: 'Equipment',
  },
  113: {
    id: 113,
    name: 'Iron Boots',
    color: '#ced5cb',
    armor: 3,
    protection: 2,
    durability: 195,
    category: 'Equipment',
  },
  114: {
    id: 114,
    name: 'Shield',
    color: '#b99a68',
    shield: true,
    durability: 336,
    category: 'Equipment',
  },
};
Object.assign(ITEMS, {
  120: { name: 'Raw Mutton', color: '#c66062', food: 2, saturation: 0.3, meat: true },
  121: { name: 'Cooked Mutton', color: '#996141', food: 6, saturation: 0.8, meat: true },
  122: { name: 'Raw Beef', color: '#bb4247', food: 3, saturation: 0.3, meat: true },
  123: { name: 'Steak', color: '#965137', food: 8, saturation: 0.8, meat: true },
  124: { name: 'Raw Porkchop', color: '#e5908e', food: 3, saturation: 0.3, meat: true },
  125: { name: 'Cooked Porkchop', color: '#c08b60', food: 8, saturation: 0.8, meat: true },
  126: { name: 'Raw Chicken', color: '#ecc5ae', food: 2, saturation: 0.3, meat: true },
  127: { name: 'Cooked Chicken', color: '#c28a4a', food: 6, saturation: 0.6, meat: true },
  128: { name: 'Rotten Flesh', color: '#997347', food: 4, saturation: 0.1, meat: true },
  129: { name: 'Flint', color: '#51545b', category: 'Materials' },
  130: {
    name: 'Flint and Steel',
    color: '#b8bec3',
    durability: 64,
    igniter: true,
    category: 'Tools',
  },
  131: { name: 'Gold Ingot', color: '#efd069', category: 'Materials' },
  132: { name: 'Leather', color: '#a76e40', category: 'Materials' },
  133: { name: 'Feather', color: '#f0ead9', category: 'Materials' },
  134: { name: 'Bone', color: '#dcd9b8', category: 'Materials' },
  135: { name: 'Blaze Rod', color: '#f4b13c', category: 'Materials' },
  137: { name: 'Quartz', color: '#ebd9ca', category: 'Materials' },
  138: { name: 'Gold Nugget', color: '#edc65a', category: 'Materials' },
  139: { name: 'Nether Brick', color: '#5c3338', category: 'Materials' },
  150: {
    name: 'Golden Helmet',
    color: '#efc84f',
    armor: 0,
    protection: 2,
    durability: 77,
    gold: true,
    category: 'Equipment',
  },
});
for (const [offset, kind] of [
  'zombie',
  'cow',
  'pig',
  'sheep',
  'chicken',
  'blaze',
  'piglin',
  'skeleton',
  'creeper',
  'spider',
  'brute',
  'wither_skeleton',
].entries()) {
  ITEMS[160 + offset] = {
    name: `${kind.replaceAll('_', ' ')} spawn egg`,
    color: '#8aa565',
    spawn: kind,
    category: 'Mobs',
  };
}
for (const [id, item] of Object.entries(ITEMS)) {
  item.id = Number(id);
  item.category ??= item.food ? 'Supplies' : 'Materials';
}
export const CREATIVE_ITEMS = Object.keys(ITEMS)
  .map(Number)
  .filter((id) => id !== B.AIR && id !== B.BEDROCK && !ITEMS[id].hidden);

export function isSolid(id) {
  return Boolean(BLOCKS[id]?.solid);
}
export function tileFor(id, face) {
  const b = BLOCKS[id];
  return b?.tiles?.[face] ?? b?.tile ?? 0;
}
export function canCraft(bag, recipe) {
  return recipe.ingredients.every(([id, n]) => (bag[id] || 0) >= n);
}
export function craft(bag, recipe) {
  if (!canCraft(bag, recipe)) return false;
  for (const [id, n] of recipe.ingredients) bag[id] -= n;
  bag[recipe.output] = (bag[recipe.output] || 0) + recipe.count;
  return true;
}
